from abc import abstractmethod
from pydantic.v1 import Field, validator
from tidy3d.components.base import Tidy3dBaseModel
from tidy3d.components.types import ArrayComplex1D, ArrayFloat1D
from typing import Literal, Union, Optional, Any
import skrf as rf
from skrf.media import Media, device
from Src.Models.Media import TransmissionLine

class AbstractComponent(Tidy3dBaseModel):
    """Abstract base class for all media components"""
    frequency: ArrayFloat1D = Field(
        ...,
        title="Frequency",
        description="Frequency points in Hz",
        example=[1e9, 2e9, 3e9]
    )
    z0: Optional[Union[complex, ArrayComplex1D]] = Field(
        50,
        title="Characteristic Impedance",
        description="Complex characteristic Impedance (n_freqs, complex)",
        example=50+0j
    )
    z0_port: Optional[Union[complex, ArrayComplex1D]] = Field(
        50,
        title="Port Impedance",
        description="z0_port is the port impedance for networks generated by the media. If z0_port is not None, the networks generated by the media are renormalized (or in other words embedded) from the characteristic impedance Z0 of the media to z0_port. Else if z0_port is None, the networks port impedances will be the raw characteristic impedance Z0 of the media.",
        example=50+0j
    )
    type: str = Field(
        ...,
        title="Component Type",
        description="Type of component"
    )

    def __init__(self, **data: Any):
        super().__init__(**data)
    
    @abstractmethod
    def to_network(self, media: Optional[TransmissionLine] = None) -> rf.Network:
        """Convert to scikit-rf Network object
        
        Args:
            media: Optional scikit-rf Media object. If provided, use this media to create the network.
                  If not provided, create media using to_media() method.
        
        Returns:
            rf.Network: A scikit-rf Network object representing this media
        """
        raise NotImplementedError
    
    def to_media(self, media: Optional[TransmissionLine] = None) -> Media:
        """Convert to scikit-rf Media object
        
        Args:
            media: Optional TransmissionLine object. If provided, use this media to create the media.
                  If not provided, create media using to_media() method.
        
        Returns:
            rf.Media: A scikit-rf Media object representing this media
        """
        if self.frequency is None:
            raise ValueError("frequency must be specified")
        if self.z0 is None:
            raise ValueError("z0 must be specified")
        if self.z0_port is None:
            raise ValueError("z0_port must be specified")
        if media is None:
            frequency = rf.Frequency.from_f(self.frequency,unit='Hz')
            media = rf.media.DefinedGammaZ0(frequency=frequency, z0=self.z0, z0_port=self.z0_port)
        else:
            media = media.updated_copy(
                frequency=self.frequency,
                z0=self.z0,
                z0_port=self.z0_port
            ).to_rf_media()
        return media

class R(AbstractComponent):
    """Resistor component"""
    r: Union[float, ArrayFloat1D] = Field(
        ...,
        title="Resistance",
        description="Resistance value in ohms"
    )
    type: Literal['R'] = Field(
        'R',
        title="Type",
        description="Type of component",
        frozen=True
    )

    @validator('r', pre=True)
    def validate_r_length(cls, v, values):
        if hasattr(v, '__len__') and 'frequency' in values:
            if len(v) != len(values['frequency']):
                raise ValueError("Length of resistance array must match the number of frequency points")
        return v

    def to_network(self, media: Optional[TransmissionLine] = None) -> rf.Network:
        media = self.to_media(media)
        return media.resistor(self.r)

class L(AbstractComponent):
    """Inductor component"""
    l: Union[float, ArrayFloat1D] = Field(
        ...,
        title="Inductance",
        description="Inductance value in henries"
    )
    f_0: Optional[float] = Field(
        None,
        title="Resonant Frequency",
        description="Resonant frequency, in Hz"
    )
    q_factor: Optional[float] = Field(
        None,
        title="Quality Factor",
        description="Quality factor of inductor"
    )
    r_dc: Optional[float] = Field(
        None,
        title="DC Resistance",
        description="DC resistance of inductor, in Ohms"
    )
    type: Literal['L'] = Field(
        'L',
        title="Type",
        description="Type of component",
        frozen=True
    )

    @validator('l', pre=True)
    def validate_l_length(cls, v, values):
        if hasattr(v, '__len__') and 'frequency' in values:
            if len(v) != len(values['frequency']):
                raise ValueError("Length of inductance array must match the number of frequency points")
        return v

    def to_network(self, media: Optional[TransmissionLine] = None) -> rf.Network:
        media = self.to_media(media)
        if self.f_0 is None and self.q_factor is None:
            return media.inductor(self.l)
        elif self.f_0 is not None and self.q_factor is not None:
            if self.r_dc is not None:
                return media.inductor_q(self.l, f_0=self.f_0, q_factor=self.q_factor, r_dc=self.r_dc)
            else:
                return media.inductor_q(self.l, f_0=self.f_0, q_factor=self.q_factor)
        else:
            raise ValueError("f_0 and q_factor must be both specified or both None")

class C(AbstractComponent):
    """Capacitor component"""
    c: Union[float, ArrayFloat1D] = Field(
        ...,
        title="Capacitance",
        description="Capacitance value in farads"
    )
    f_0: Optional[float] = Field(
        None,
        title="Resonant Frequency",
        description="Resonant frequency, in Hz"
    )
    q_factor: Optional[float] = Field(
        None,
        title="Quality Factor",
        description="Quality factor of capacitor"
    )
    r_dc: Optional[float] = Field(
        None,
        title="DC Resistance",
        description="DC resistance of capacitor, in Ohms"
    )
    type: Literal['C'] = Field(
        'C',
        title="Type",
        description="Type of component",
        frozen=True
    )

    @validator('c', pre=True)
    def validate_c_length(cls, v, values):
        if hasattr(v, '__len__') and 'frequency' in values:
            if len(v) != len(values['frequency']):
                raise ValueError("Length of capacitance array must match the number of frequency points")
        return v

    def to_network(self, media: Optional[TransmissionLine] = None) -> rf.Network:
        media = self.to_media(media)
        if self.f_0 is None and self.q_factor is None:
            return media.capacitor(self.c)
        elif self.f_0 is not None and self.q_factor is not None:
            if self.r_dc is not None:
                return media.capacitor_q(self.c, f_0=self.f_0, q_factor=self.q_factor, r_dc=self.r_dc)
            else:
                return media.capacitor_q(self.c, f_0=self.f_0, q_factor=self.q_factor)
        else:
            raise ValueError("f_0 and q_factor must be both specified or both None")

class G(AbstractComponent):
    """Conductor component"""
    g: Union[float, ArrayFloat1D] = Field(
        ...,
        title="Conductance",
        description="Conductance value in Siemens"
    )
    type: Literal['G'] = Field(
        'G',
        title="Type",
        description="Type of component",
        frozen=True
    )

    @validator('g', pre=True)
    def validate_g_length(cls, v, values):
        if hasattr(v, '__len__') and 'frequency' in values:
            if len(v) != len(values['frequency']):
                raise ValueError("Length of conductance array must match the number of frequency points")
        return v

    def to_network(self, media: Optional[TransmissionLine] = None) -> rf.Network:
        media = self.to_media(media)
        return media.shunt_resistor(self.g)

RLGC = Union[R, L, G, C]

class Attenuator(AbstractComponent):
    """Attenuator component"""
    s21: Union[float, ArrayFloat1D] = Field(
        ...,
        title="S21 Attenuation",
        description="S21 attenuation factor"
    )
    db: Optional[bool] = Field(
        False,
        title="Use dB",
        description="If True, s21 is in dB"
    )
    d: Optional[float] = Field(
        0,
        title="Length",
        description="Length of attenuator"
    )
    unit: Optional[str] = Field(
        'deg',
        title="Length Unit",
        description="Length unit of d, which can be 'deg','rad','m','cm','um','in','mil','s','us','ns','ps'"
    )
    type: Literal['Attenuator'] = Field(
        'Attenuator',
        title="Type",
        description="Type of component",
        frozen=True
    )

    @validator('s21', pre=True)
    def validate_s21_length(cls, v, values):
        if hasattr(v, '__len__') and 'frequency' in values:
            if len(v) != len(values['frequency']):
                raise ValueError("Length of s21 array must match the number of frequency points")
        return v

    def to_network(self, media: Optional[TransmissionLine] = None) -> rf.Network:
        media = self.to_media(media)
        return media.attenuator(self.s21, self.db, self.d, self.unit)

class Isolator(AbstractComponent):
    """Isolator component"""
    source_port: Optional[int] = Field(
        0,
        title="Source Port",
        description="Port at which power can flow from, which can be 0 or 1"
    )
    type: Literal['Isolator'] = Field(
        'Isolator',
        title="Type",
        description="Type of component",
        frozen=True
    )
    
    def to_network(self, media: Optional[TransmissionLine] = None) -> rf.Network:
        media = self.to_media(media)
        if self.source_port not in [0, 1]:
            raise ValueError("source_port must be 0 or 1")
        return media.isolator(self.source_port)

class Splitter(AbstractComponent):
    """Splitter component"""
    nports: int = Field(
        3,
        title="Number of Ports",
        description="Number of ports in the splitter",
        ge=3
    )
    type: Literal['Splitter'] = Field(
        'Splitter',
        title="Type",
        description="Type of component",
        frozen=True
    )    
    def to_network(self, media: Optional[TransmissionLine] = None) -> rf.Network:
        media = self.to_media(media)
        return media.splitter(self.nports)

class Coupler(AbstractComponent):
    """
    Coupler component
    The resultant ntwk port assignment is as follows:
        * 0 - insertion
        * 1 - transmit
        * 2 - coupled
        * 3 - isolated
    """
    db: float = Field(
        3,
        title="Coupling Value",
        description="The magnitude of the coupling value (in dB), sign doesn't matter"
    )
    deg: float = Field(
        0,
        title="Phase",
        description="Coupling phase (in degrees)"
    )
    type: Literal['Coupler'] = Field(
        'Coupler',
        title="Type",
        description="Type of component",
        frozen=True
    )
    @validator('db')
    def validate_db(cls, v):
        if not isinstance(v, (int, float)):
            raise ValueError('Coupling value must be numeric')
        return abs(float(v))
        
    @validator('deg')
    def validate_deg(cls, v):
        if not isinstance(v, (int, float)):
            raise ValueError('Phase offset must be an integer')
        return v % 360
    
    def to_network(self, media: Optional[TransmissionLine] = None) -> rf.Network:
        media = self.to_media(media)
        coupler = device.MatchedSymmetricCoupler.from_dbdeg(db=self.db, deg=self.deg, media=media)
        return coupler.ntwk
    
Microwave = Union[Attenuator, Isolator, Splitter, Coupler]

class Port(AbstractComponent):
    """Port component"""
    name: str = Field(
        ...,
        title="Name",
        description="Port name"
    )
    type: Literal['Port'] = Field(
        'Port',
        title="Type",
        description="Type of component",
        frozen=True
    )

    def to_network(self, z0_port: float = 50) -> rf.Network:
        frequency = rf.Frequency.from_f(self.frequency,unit='Hz')
        port = rf.Circuit.Port(frequency=frequency, z0=z0_port, name=self.name)
        return port

class Ground(AbstractComponent):
    """Ground component"""
    name: str = Field(
        ...,
        title="Name",
        description="Ground name"
    )
    type: Literal['Ground'] = Field(
        'Ground',
        title="Type",
        description="Type of component",
        frozen=True
    )
    
    def to_network(self, z0_port: float = 50) -> rf.Network:
        frequency = rf.Frequency.from_f(self.frequency,unit='Hz')
        gnd = rf.Circuit.Ground(frequency=frequency, z0=z0_port, name=self.name)
        return gnd

class Open(AbstractComponent):
    """Open component"""
    name: str = Field(
        ...,
        title="Name",
        description="Open name"
    )
    type: Literal['Open'] = Field(
        'Open',
        title="Type",
        description="Type of component",
        frozen=True
    )
    
    def to_network(self, z0_port: float = 50) -> rf.Network:
        frequency = rf.Frequency.from_f(self.frequency,unit='Hz')
        open = rf.Circuit.Open(frequency=frequency, z0=z0_port, name=self.name)
        return open

SimComponent = Union[Port, Ground, Open]