from pydantic.v1 import Field, validator
from abc import abstractmethod
from typing import List, Union, Literal, Optional, Any
from tidy3d.components.base import Tidy3dBaseModel
from tidy3d.components.types import ArrayComplex1D, ArrayFloat1D
from skrf.media import (Coaxial, RectangularWaveguide, MLine, CPW, Freespace,
    CircularWaveguide, DefinedGammaZ0, DefinedAEpTandZ0, DistributedCircuit, Media)
from skrf.frequency import Frequency
import numpy as np

class AbstractMedia(Tidy3dBaseModel):
    """Abstract base class for all media components"""
    frequency: ArrayFloat1D = Field(
        ...,
        title="Frequency",
        description="Frequency points in Hz",
        example=[1e9, 2e9, 3e9]
    )
    z0: Optional[Union[complex, ArrayComplex1D]] = Field(
        50,
        title="Characteristic Impedance",
        description="Complex characteristic Impedance (n_freqs, complex)",
        example=50+0j
    )
    z0_port: Optional[Union[complex, ArrayComplex1D]] = Field(
        50,
        title="Port Impedance",
        description="z0_port is the port impedance for networks generated by the media. If z0_port is not None, the networks generated by the media are renormalized (or in other words embedded) from the characteristic impedance Z0 of the media to z0_port. Else if z0_port is None, the networks port impedances will be the raw characteristic impedance Z0 of the media.",
        example=50+0j
    )
    type: Literal['AbstractMedia'] = Field(
        'AbstractMedia',
        title="Type",
        description="Type of media",
        frozen=True
    )

    def __init__(self, **data: Any):
        super().__init__(**data)
    
    @abstractmethod
    def to_rf_media(self) -> Media:
        """Convert to scikit-rf Media object"""
        raise NotImplementedError


class CoaxialLine(AbstractMedia):
    """Coaxial transmission line"""
    dinner: float = Field(
        ...,
        title="Inner Diameter",
        description="Inner conductor diameter, in meters"
    )
    douter: float = Field(
        ...,
        title="Outer Diameter",
        description="Outer conductor diameter, in meters"
    )
    epsilon_r: Optional[float] = Field(
        1.0,
        title="Relative Permittivity",
        description="Relative permittivity of dielectric. Default is 1.0 (air)"
    )
    tan_delta: Optional[float] = Field(
        0.0,
        title="Loss Tangent",
        description="Loss tangent of dielectric. Default is 0.0 (non lossy dielectric)"
    )
    sigma: Optional[float] = Field(
        np.inf,
        title="Conductivity",
        description="Conductors electrical conductivity, in S/m. Default is infinity (non lossy metal)."
    )
    type: Literal['CoaxialLine'] = Field(
        'CoaxialLine',
        title="Type",
        description="Type of transmission line",
        frozen=True
    )

    @validator('dinner')
    def validate_inner_diameter(cls, v):
        if v <= 0:
            raise ValueError("Inner diameter must be positive")
        return v

    @validator('douter')
    def validate_outer_diameter(cls, v, values):
        if v <= 0:
            raise ValueError("Outer diameter must be positive")
        if 'dinner' in values and v <= values['dinner']:
            raise ValueError("Outer diameter must be greater than inner diameter")
        return v

    @validator('epsilon_r')
    def validate_epsilon_r(cls, v):
        if v <= 0:
            raise ValueError("Relative permittivity must be positive")
        return v

    @validator('tan_delta')
    def validate_tan_delta(cls, v):
        if v < 0:
            raise ValueError("Loss tangent must be non-negative")
        return v

    @validator('sigma')
    def validate_sigma(cls, v):
        if v <= 0 and v != float('inf'):
            raise ValueError("Conductivity must be positive or infinity")
        return v

    def to_rf_media(self) -> Coaxial:
        """Convert to scikit-rf Coaxial object"""
        frequency = Frequency.from_f(self.frequency, unit='Hz')
        coax = Coaxial(
            frequency=frequency,
            z0=self.z0,
            Dint=self.dinner,
            Dout=self.douter,
            epsilon_r=self.epsilon_r,
            tan_delta=self.tan_delta,
            sigma=self.sigma
        )
        return coax


class RWG(AbstractMedia):
    """Rectangular waveguide transmission line"""
    a: float = Field(
        1,
        title="Width",
        description="Width of waveguide, in meters. Default is 1."
    )
    b: Optional[float] = Field(
        None,
        title="Height",
        description="Height of waveguide, in meters. If None defaults to a/2. Default is None"
    )
    
    @validator('a')
    def validate_width(cls, v):
        if v <= 0:
            raise ValueError("Width must be positive")
        return v
    
    @validator('b')
    def validate_height(cls, v):
        if v is not None and v <= 0:
            raise ValueError("Height must be positive")
        return v
    
    @validator('m')
    def validate_m(cls, v):
        if v < 0:
            raise ValueError("Mode index m must be non-negative")
        return v
    
    @validator('n')
    def validate_n(cls, v):
        if v < 0:
            raise ValueError("Mode index n must be non-negative")
        return v
    
    @validator('mode_type')
    def validate_mode_type(cls, v):
        if v not in ['TE', 'TM']:
            raise ValueError("Mode type must be either 'TE' or 'TM'")
        return v

    @validator('rho')
    def validate_rho(cls, v):
        if v is not None and v <= 0:
            raise ValueError("Resistivity must be positive")
        return v

    @validator('roughness')
    def validate_roughness(cls, v):
        if v is not None and v <= 0:
            raise ValueError("Roughness must be positive")
        return v

    m: int = Field(
        1,
        title="Horizontal Mode Index",
        description="Mode index along 'a' direction"
    )
    n: int = Field(
        0,
        title="Vertical Mode Index",
        description="Mode index along 'b' direction"
    )
    mode_type: Literal['TE', 'TM'] = Field(
        'TE',
        title="Mode Type",
        description="Mode type, either TE or TM"
    )
    ep_r: Union[float, ArrayFloat1D] = Field(
        1.0,
        title="Relative Permittivity",
        description="Relative permittivity of dielectric. If array-like must be same length as frequency. Default is 1.0"
    )
    mu_r: Union[float, ArrayFloat1D] = Field(
        1.0,
        title="Relative Permeability",
        description="Relative permeability of dielectric. If array-like must be same length as frequency. Default is 1.0"
    )
    rho: Optional[Union[float, ArrayFloat1D]] = Field(
        None,
        title="Resistivity",
        description="Resistivity of conductor (default is copper). If array-like must be same length as frequency. Default is None"
    )
    roughness: Optional[Union[float, ArrayFloat1D]] = Field(
        None,
        title="Surface Roughness",
        description="Resistivity (ohm-m) of the conductor walls. If array-like must be same length as frequency. if str, it must be a key in skrf.data.materials"
    )
    type: Literal['RWG'] = Field(
        'RWG',
        title="Type",
        description="Type of transmission line",
        frozen=True
    )

    def to_rf_media(self) -> RectangularWaveguide:
        """Convert to scikit-rf RectangularWaveguide object"""
        frequency = Frequency.from_f(self.frequency, unit='Hz')
        waveguide = RectangularWaveguide(
            frequency=frequency,
            z0=self.z0,
            a=self.a,
            b=self.b,
            ep_r=self.ep_r,
            mu_r=self.mu_r,
            rho=self.rho,
            mode_type=self.mode_type,
            m=self.m,
            n=self.n,
            roughness=self.roughness
        )
        return waveguide


class CWG(AbstractMedia):
    """Circular waveguide transmission line"""
    r: float = Field(
        ...,
        title="Radius",
        description="Radius of waveguide, in meters"
    )
    ep_r: Union[float, ArrayFloat1D] = Field(
        1.0,
        title="Relative Permittivity",
        description="Filling material’s relative permittivity. Default is 1.0 (air)"
    )
    mu_r: Union[float, ArrayFloat1D] = Field(
        1.0,
        title="Relative Permeability",
        description="Filling material’s relative permeability. Default is 1.0"
    )
    mode_type: Literal['te', 'tm'] = Field(
        'te',
        title="Mode Type",
        description="Mode type, either 'te' or 'tm'. Default is 'te'"
    )
    m: int = Field(
        1,
        title="Azimuthal Mode Index",
        description="Azimuthal mode index along 'phi' direction. Default is 1"
    )
    n: int = Field(
        1,
        title="Radial Mode Index",
        description="Radial mode index along 'r' direction. Default is 1"
    )
    rho: Optional[Union[float, ArrayFloat1D]] = Field(
        None,
        title="Resistivity",
        description="Resistivity (ohm-m) of the conductor walls. Default is None"
    )
    type: Literal['CWG'] = Field(
        'CWG',
        title="Type",
        description="Type of transmission line",
        frozen=True
    )

    @validator('r')
    def validate_radius(cls, v):
        if v <= 0:
            raise ValueError("Radius must be positive")
        return v

    @validator('ep_r')
    def validate_ep_r(cls, v):
        if v < 1:
            raise ValueError("Relative permittivity must be greater than 1")
        return v

    @validator('mu_r')
    def validate_mu_r(cls, v):
        if v < 1:
            raise ValueError("Relative permeability must be greater than 1")
        return v

    @validator('m')
    def validate_m(cls, v):
        if v < 0:
            raise ValueError("Mode index m must be non-negative")
        return v

    @validator('n')
    def validate_n(cls, v):
        if v < 1:
            raise ValueError("Mode index n must be positive")
        return v

    def to_rf_media(self) -> CircularWaveguide:
        """Convert to scikit-rf CircularWaveguide object"""
        frequency = Frequency.from_f(self.frequency, unit='Hz')
        waveguide = CircularWaveguide(
            frequency=frequency,
            z0=self.z0,
            r=self.r,
            ep_r=self.ep_r,
            mu_r=self.mu_r,
            rho=self.rho,
            mode_type=self.mode_type,
            m=self.m,
            n=self.n,
        )
        return waveguide


class CPWLine(AbstractMedia):
    """Coplanar waveguide transmission line"""
    w: float = Field(
        3e-3,
        title="Width",
        description="Center conductor width, in meters"
    )
    s: float = Field(
        0.3e-3,
        title="Gap",
        description="Gap between center conductor and ground planes, in meters"
    )
    h: float = Field(
        1.55,
        title="Substrate Height",
        description="Substrate height, in meters. Default is 1.55(equivalent to infinite height for default w and s)"
    )
    t: Optional[float] = Field(
        None,
        title="Metal Thickness",
        description="Metal thickness, in meters. Default is None"
    )
    ep_r: Union[float, ArrayFloat1D] = Field(
        4.5,
        title="Relative Permittivity",
        description="Relative permittivity of substrate. Default is 4.5"
    )
    tand: Union[float, ArrayFloat1D] = Field(
        0.0,
        title="Loss Tangent",
        description="Loss tangent of substrate. Default is 0.0"
    )
    rho: Optional[Union[float, ArrayFloat1D]] = Field(
        1.68e-8,
        title="Resistivity",
        description="Conductor resistivity in ohm-meters. Default is 1.68e-8 (copper)"
    )
    has_metal_backside: bool = Field(
        False,
        title="Has Metal Backside",
        description="Whether the substrate has a metal backside. Default is False"
    )
    diel: Literal['djordjevicsvensson', 'frequencyinvariant'] = Field(
        'djordjevicsvensson',
        title="Dielectric Model",
        description="Dielectric model to use. Default is 'djordjevicsvensson'"
    )
    f_low: Union[float, ArrayFloat1D] = Field(
        1e3,
        title="Low Frequency",
        description="Lower frequency for wideband Debye Djordjevic/Svensson dielectric model. Default is 1 kHz"
    )
    f_high: Union[float, ArrayFloat1D] = Field(
        1e12,
        title="High Frequency",
        description="Higher frequency for wideband Debye Djordjevic/Svensson dielectric model. Default is 1 THz"
    )
    f_epr_tand: Union[float, ArrayFloat1D] = Field(
        1e9,
        title="Frequency of EPR and Tand",
        description="Measurement frequency for ep_r and tand of dielectric, in Hz. Default is 1 GHz"
    )
    compatibility_mode: Optional[str] = Field(
        None,
        title="Compatibility Mode",
        description="""
        Compatibility mode to use. Default is None
        If set to 'qucs', following behaviour happens :

        * Characteristic impedance will be real (no imaginary part due to tand)
        """
    )
    type: Literal['CPWLine'] = Field(
        'CPWLine',
        title="Type",
        description="Type of transmission line",
        frozen=True
    )

    @validator('w')
    def validate_width(cls, v):
        if v <= 0:
            raise ValueError("Width must be positive")
        return v

    @validator('s')
    def validate_gap(cls, v):
        if v <= 0:
            raise ValueError("Gap must be positive")
        return v

    @validator('h')
    def validate_height(cls, v):
        if v <= 0:
            raise ValueError("Height must be positive")
        return v

    @validator('ep_r')
    def validate_ep_r(cls, v):
        if v < 1:
            raise ValueError("Relative permittivity must be greater than 1")
        return v

    @validator('tand')
    def validate_tand(cls, v):
        if v < 0:
            raise ValueError("Loss tangent must be non-negative")
        return v

    @validator('f_low', 'f_high', 'f_epr_tand')
    def validate_frequencies(cls, v, values, field):
        if v <= 0:
            if field.name == 'f_low':
                raise ValueError("Low frequency must be positive")
            elif field.name == 'f_high':
                raise ValueError("High frequency must be positive")
            else:
                raise ValueError("Measurement frequency must be positive")
        if field.name == 'f_high' and 'f_low' in values and v <= values['f_low']:
            raise ValueError("High frequency must be greater than low frequency")
        return v

    def to_rf_media(self) -> CPW:
        """Convert to scikit-rf CPW object"""
        frequency = Frequency.from_f(self.frequency, unit='Hz')
        cpw = CPW(
            frequency=frequency,
            z0=self.z0,
            w=self.w,
            s=self.s,
            h=self.h,
            ep_r=self.ep_r,
            t=self.t,
            tand=self.tand,
            rho=self.rho,
            has_metal_backside=self.has_metal_backside
        )
        return cpw


class MicrostripLine(AbstractMedia):
    """Microstrip transmission line"""
    w: float = Field(
        ...,
        title="Width",
        description="Width of conductor, in meters"
    )
    h: float = Field(
        ...,
        title="Height",
        description="Height of substrate between ground plane and conductor, in meters"
    )
    t: Optional[float] = Field(
        None,
        title="Metal Thickness",
        description="Conductor thickness, in meters. Default is None (no width correction to account strip thickness)"
    )
    ep_r: Union[float, ArrayFloat1D] = Field(
        4.5,
        title="Relative Permittivity",
        description="Relative permittivity of dielectric at frequency f_epr_tand. Default is 4.5"
    )
    mu_r: Union[float, ArrayFloat1D] = Field(
        1.0,
        title="Relative Permeability",
        description="Relative permeability of dielectric. Default is 1.0"
    )
    model: Literal['hammerstadjensen', 'schneider', 'wheeler'] = Field(
        'hammerstadjensen',
        title="Impedance Model",
        description="Microstripline quasi-static impedance and dielectric model"
    )
    disp: Literal['hammerstadjensen', 'kirschningjansen', 'kobayashi', 'schneider', 'yamashita', 'none'] = Field(
        'kirschningjansen',
        title="Dispersion Model",
        description="Microstripline impedance and dielectric frequency dispersion model"
    )
    tand: Union[float, ArrayFloat1D] = Field(
        0.0,
        title="Loss Tangent",
        description="Loss tangent of substrate. Default is 0.0"
    )
    rho: Optional[Union[float, ArrayFloat1D]] = Field(
        1.68e-8,
        title="Resistivity",
        description="Conductor resistivity in ohm-meters. Default is 1.68e-8 (copper)"
    )
    rough: Optional[Union[float, ArrayFloat1D]] = Field(
        None,
        title="Surface Roughness",
        description="Surface roughness of conductor in meters. Default is None"
    )
    diel: Literal['djordjevicsvensson', 'frequencyinvariant'] = Field(
        'djordjevicsvensson',
        title="Dielectric Model",
        description="Dielectric model to use. Default is 'djordjevicsvensson'"
    )
    f_low: Union[float, ArrayFloat1D] = Field(
        1e3,
        title="Low Frequency",
        description="Lower frequency for wideband Debye Djordjevic/Svensson dielectric model. Default is 1 kHz"
    )
    f_high: Union[float, ArrayFloat1D] = Field(
        1e12,
        title="High Frequency",
        description="Higher frequency for wideband Debye Djordjevic/Svensson dielectric model. Default is 1 THz"
    )
    f_epr_tand: Union[float, ArrayFloat1D] = Field(
        1e9,
        title="Frequency of EPR and Tand",
        description="Measurement frequency for ep_r and tand of dielectric, in Hz. Default is 1 GHz"
    )
    compatibility_mode: Optional[Literal['qucs', None]] = Field(
        None,
        title="Compatibility Mode",
        description="""
        Compatibility mode for scikit-rf. Default is None.
        If set to 'qucs', following behavious happens :

        * Characteristic impedance will be real (no imaginary part due to tand)
        * Quasi-static relative permittivity and impedance will by used for
          loss computation instead of frequency-dispersed values
        *  Kobayashi and Yamashita models will disperse permittivity but keep
           quasi-static impedance values
        """
    )
    type: Literal['MicrostripLine'] = Field(
        'MicrostripLine',
        title="Type",
        description="Type of transmission line",
        frozen=True
    )

    @validator('w')
    def validate_width(cls, v):
        if v <= 0:
            raise ValueError("Width must be positive")
        return v

    @validator('h')
    def validate_height(cls, v):
        if v <= 0:
            raise ValueError("Height must be positive")
        return v

    @validator('t')
    def validate_thickness(cls, v):
        if v is not None and v <= 0:
            raise ValueError("Thickness must be positive")
        return v

    @validator('ep_r')
    def validate_ep_r(cls, v):
        if v <= 1:
            raise ValueError("Relative permittivity must be greater than 1")
        return v

    @validator('mu_r')
    def validate_mu_r(cls, v):
        if v < 1:
            raise ValueError("Relative permeability must be greater than or equal to 1")
        return v

    @validator('tand')
    def validate_tand(cls, v):
        if v < 0:
            raise ValueError("Loss tangent must be non-negative")
        return v

    @validator('rho')
    def validate_rho(cls, v):
        if v is not None and v <= 0:
            raise ValueError("Resistivity must be positive")
        return v

    @validator('rough')
    def validate_rough(cls, v):
        if v is not None and v <= 0:
            raise ValueError("Surface roughness must be positive")
        return v

    @validator('f_low', 'f_high', 'f_epr_tand')
    def validate_frequencies(cls, v, values, field):
        if v <= 0:
            raise ValueError(f"{field.name} must be positive")
        if field.name == 'f_high' and 'f_low' in values:
            if v <= values['f_low']:
                raise ValueError("f_high must be greater than f_low")
        return v

    def to_rf_media(self) -> MLine:
        """Convert to scikit-rf MLine object"""
        frequency = Frequency.from_f(self.frequency, unit='Hz')
        mline = MLine(
            frequency=frequency,
            z0=self.z0,
            w=self.w,
            h=self.h,
            t=self.t,
            ep_r=self.ep_r,
            mu_r=self.mu_r,
            model=self.model,
            disp=self.disp,
            tand=self.tand,
            rho=self.rho,
            rough=self.rough,
            diel=self.diel,
            f_low=self.f_low,
            f_high=self.f_high,
            f_epr_tand=self.f_epr_tand
        )
        return mline


class DistributedRLGC(AbstractMedia):
    """Distributed circuit transmission line defined by RLGC parameters"""
    R: Union[float, ArrayFloat1D] = Field(
        0.0,
        title="Resistance",
        description="Series resistance per unit length, in ohms/meter. Default is 0.0"
    )
    L: Union[float, ArrayFloat1D] = Field(
        1e-9,
        title="Inductance",
        description="Series inductance per unit length, in henries/meter. Default is 1nH/m"
    )
    G: Union[float, ArrayFloat1D] = Field(
        0.0,
        title="Conductance",
        description="Shunt conductance per unit length, in siemens/meter. Default is 0.0"
    )
    C: Union[float, ArrayFloat1D] = Field(
        1e-12,
        title="Capacitance",
        description="Shunt capacitance per unit length, in farads/meter. Default is 1pF/m"
    )
    type: Literal['DistributedRLGC'] = Field(
        'DistributedRLGC',
        title="Type",
        description="Type of transmission line",
        frozen=True
    )

    @validator('R')
    def validate_resistance(cls, v):
        if isinstance(v, np.ndarray):
            if (v < 0).any():
                raise ValueError("Resistance must be non-negative")
        elif v < 0:
            raise ValueError("Resistance must be non-negative")
        return v

    @validator('G')
    def validate_conductance(cls, v):
        if isinstance(v, np.ndarray):
            if (v < 0).any():
                raise ValueError("Conductance must be non-negative")
        elif v < 0:
            raise ValueError("Conductance must be non-negative")
        return v

    @validator('L')
    def validate_inductance(cls, v):
        if isinstance(v, np.ndarray):
            if (v <= 0).any():
                raise ValueError("Inductance must be positive")
        elif v <= 0:
            raise ValueError("Inductance must be positive")
        return v

    @validator('C')
    def validate_capacitance(cls, v):
        if isinstance(v, np.ndarray):
            if (v <= 0).any():
                raise ValueError("Capacitance must be positive")
        elif v <= 0:
            raise ValueError("Capacitance must be positive")
        return v

    def to_rf_media(self) -> DistributedCircuit:
        """Convert to scikit-rf DistributedCircuit object"""
        frequency = Frequency.from_f(self.frequency, unit='Hz')
        media = DistributedCircuit(
            frequency=frequency,
            z0=self.z0,
            R=self.R,
            L=self.L,
            G=self.G,
            C=self.C,
        )
        return media

# Define a union type for all transmission line media
TransmissionLine = Union[CoaxialLine, RWG, CWG, CPWLine, MicrostripLine, DistributedRLGC]